name: CI Pipeline for Flask App with Redis

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Build Docker image
      run: docker build . -t myapp:v1  # Build the image

    - name: Install Docker Compose
      run: sudo apt-get install -y docker-compose  # Install Docker Compose

    - name: Run Docker Compose
      run: docker-compose up -d  # Use docker-compose.yaml to start Redis and Flask services

    # Optional test step if you have any tests for your app
    - name: Run tests
      run: docker exec <project_flask_1> pytest  # Run tests inside the Flask container


