name: CI Pipeline

on:
  push:
    branches:
      - main  # Make sure you're working on this branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # v3 is the latest and should be compatible

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # v2 is the latest and should be compatible

    - name: Build Docker image
      run: docker build . -t your_dockerhub_username/myapp:latest

    - name: Run Tests
      run: |
        echo "No tests to run yet."
