name: CI Pipeline for Flask App with Redis

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
            
    - name: Docker Setup Buildx
l     uses: docker/setup-buildx-action@v3.7.1
            
    - name: Build Docker image
      run: docker build . -t your_dockerhub_username/myapp:latest
      
    - name: Run Docker Compose
      run: docker-compose up -d  # Use docker-compose.yaml to start Redis and Flask services

    # Optional test step if you have any tests for your app
    - name: Run tests
      run: docker exec <your_flask_container_name> pytest  # Run tests inside the Flask container

    - name: Push image to Docker Hub
      run: docker push your_dockerhub_username/myapp:latest  # Push the built image to Docker Hub

