name: CI Pipeline for Flask App with Redis

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1  # Use the latest stable version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1  # Use the latest stable version

    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d  # Build the images and start the services in detached mode

    - name: Run Tests
      run: |
        docker exec <flask_container_name> pytest  # Replace <flask_container_name> with the name of your Flask service/container
        # Make sure to specify the correct container name

    - name: Stop and Remove Containers
      run: |
        docker-compose down  # Stop and remove the containers

