name: CI Pipeline for Flask App with Redis

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Build Docker images
        run: docker-compose build  # Build all images defined in the docker-compose.yaml

      - name: List Docker images
        run: docker images  # List the Docker images to verify that myapp:v1 exists

      - name: Run Docker Compose
        run: docker-compose up -d  # Start the services in detached mode

      # Optional test step if you have any tests for your app
      - name: Run tests
        run: docker exec project_flask_1 pytest  # Use the correct container name for your Flask app
