name: CI Pipeline for Flask App with Redis

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and Run Docker Compose
        run: |
          docker-compose up --build -d  # Build the images and start the services in detached mode

      # Optional step to push the image to Docker Hub (if you have an account)
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #
      # - name: Push image to Docker Hub
      #   run: docker push your_dockerhub_username/myapp:v1  # Uncomment this if you want to push the image
